name: Docker Build and Push

on:
  push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
        
      - name: Replace master/main Branch Names with latest
        if: ${{ env.BRANCH_NAME }} == 'main' || ${{ env.BRANCH_NAME }} == 'master'
        shell: bash
        run: echo "BRANCH_NAME=latest" >> $GITHUB_ENV
    
      - name: Move to correct working directory for docker build
        run: |
          pwd
          ls
          cd API

      - name: Docker build and publish
        uses: zenato/docker-action@v1.0.0
        with:
          # Registry username
          username: ${{ secrets.DOCKER_USERNAME }}
          # Registry password
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Repository on registry
          repository: ${{ secrets.DOCKER_REPOSITORY }}
          # Registry hostname
          registry: ${{ secrets.DOCKER_REGISTRY }}
          # Image tag
          tag: ${{ env.BRANCH_NAME }}
