name: Docker Build and Push

on:
  push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
        
      - name: Replace master/main Branch Names with latest
        if: env.BRANCH_NAME == 'main' || env.BRANCH_NAME == 'master'
        shell: bash
        run: echo "BRANCH_NAME=latest" >> $GITHUB_ENV

      - name: Build, Tag and Publish
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name:  ${{ secrets.DOCKER_REPOSITORY }}
          tags: ${{ env.BRANCH_NAME }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./API/Dockerfile
          cache: true
